language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r base_requirements.txt
  - pip install -U pytest==3.0.5 flake8
  - pip install flask
script:
  - flake8 .
  - python -m pytest
